name: ai-math-tutor
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pillow
  - pandas
  - sentencepiece
  - matplotlib
  - tqdm
  - h5py
  - pip
  - pip:
    - torchtext
    - libjpeg-turbo
