name: ai-math-tutor
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - cpuonly      # or cudatoolkit=11.7 if you have an NVIDIA GPU
  - numpy
  - pillow
  - pandas
  - sentencepiece
  - pip
  - pip:
    - torchtext
